name: Cypress Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs: 
  cypress-run:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install deps
        run: npm ci || npm Install

      - name: Run Cypress tests (timeout protected)
        uses: cypress-io/github-action@v6
        with:
          command: npx cypress run --config pageLoadTimeout=20000, defaultCommandTimeout=10000
          wait-on-timeout: 60

      - name: Upload Cypress Artifacts 
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: |
            cypress/videos
            cypress/screenshots

