name: Cypress Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs: 
  cypress-run:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install deps
        run: npm ci || npm Install

      - name: Run Cypress (headless)
        uses: cypress-io/github-action@v6
        with:
          command: npx cypress run

      - name: Upload videos & screenshots 
        if: always()
        uses: actions/upload-arifact@v4
        with:
          name: cypress-arifacts
          path: |
            cypress/videos
            cypress/screenshots

